name: smart_rabbit
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^0.14.0+2
  google_sign_in: ^4.0.0
  firebase_core: ^0.4.0+8
  firebase_dynamic_links: ^0.3.0
  uuid: ^2.0.2
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1
  easy_localization: ^1.3.1
  flutter_screenutil: ^0.5.3
  shared_preferences: ^0.5.3+4
  intro_slider: ^2.2.7
  pin_code_text_field: ^1.3.7
  json_annotation: ^2.0.0
  http: ^0.12.0+2
  mobx: 0.3.5
  flutter_mobx: 0.3.0+1
  flutter_facebook_login: ^2.0.1
  flushbar: ^1.9.0
  provider: ^3.1.0
  google_maps_flutter: ^0.5.21
  datetime_picker_formfield: ^0.4.3
  intl: ^0.15.8
  geolocator: ^5.1.3
  permission_handler: ^3.1.0  
  flutter_google_places: ^0.2.3
  geocoder: ^0.2.1
  image_picker_modern: ^0.4.12+2
  flutter_rating_bar: ^2.0.0+2
  carousel_slider: ^1.3.0
  bubble_tab_indicator: ^0.1.4
  cloud_firestore: ^0.12.9+4
  firebase_storage: ^3.0.6
  url_launcher: ^5.1.4
  fluttertoast: ^3.1.3
  pk_skeleton: ^0.0.2
  

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.3.1
  mobx_codegen: 0.3.3+1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/i18n/vi-VN.json
    - assets/i18n/en-US.json
    - assets/images/logo_x5.png
    - assets/images/logo_x1.png
    - assets/images/easy.png
    - assets/images/speed.png
    - assets/images/convenience.png
    - assets/images/review.png
    - assets/images/vn_flag_icon.png
    - assets/images/login_banner.png
    - assets/images/send_message.png
    - assets/images/female_user.jpg
    - assets/images/house_cleaning.png
    - assets/images/garden.png
    - assets/images/go_to_market.png
    - assets/images/child_care.png
    - assets/images/laundry.png
    - assets/images/other.png
    - assets/images/avt_default.png
    - assets/images/not_found.jpg


  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Pacifico-Regular
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-Thin.ttf
          weight: 100
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 600
        - asset: assets/fonts/Roboto-Black.ttf
          weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
